CXXFLAGS = -Wall --std=c++23

1: BTH1_BT01.cpp
	g++ $(CXXFLAGS) BTH1_BT01.cpp -o .output/BT01; .output/BT01

2: BTH1_BT02.cpp
	g++ $(CXXFLAGS) BTH1_BT02.cpp -o .output/BT02; .output/BT02

3: BTH1_BT03.cpp
	g++ $(CXXFLAGS) BTH1_BT03.cpp -o .output/BT03; .output/BT03

4: BTH1_BT04.cpp
	g++ $(CXXFLAGS) BTH1_BT04.cpp -o .output/BT04; .output/BT04

5: BTH1_BT05.cpp
	g++ $(CXXFLAGS) BTH1_BT05.cpp -o .output/BT05; .output/BT05

6: BTH1_BT06.cpp
	g++ $(CXXFLAGS) BTH1_BT06.cpp -o .output/BT06; .output/BT06

7: BTH1_BT07.cpp
	g++ $(CXXFLAGS) BTH1_BT07.cpp -o .output/BT07; .output/BT07

8: BTH1_BT08.cpp
	g++ $(CXXFLAGS) BTH1_BT08.cpp -o .output/BT08; .output/BT08

9: BTH1_BT09.cpp
	g++ $(CXXFLAGS) BTH1_BT09.cpp -o .output/BT09; .output/BT09

10: BTH1_BT10.cpp
	g++ $(CXXFLAGS) BTH1_BT10.cpp -o .output/BT10; .output/BT10

11: BTH1_BT11.cpp
	g++ -Wall -std=c++17 BTH1_BT11.cpp -o .output/BT11; .output/BT11

clean:
	rm .output/*
