CXXFLAGS = -Wall --std=c++23

1: BTH2_BT01.cpp
	g++ $(CXXFLAGS) BTH2_BT01.cpp -o .output/BT01; .output/BT01

2: BTH2_BT02.cpp
	g++ $(CXXFLAGS) BTH2_BT02.cpp -o .output/BT02; .output/BT02

3: BTH2_BT03.cpp
	g++ $(CXXFLAGS) BTH2_BT03.cpp -o .output/BT03; .output/BT03

4: BTH2_BT04.cpp
	g++ $(CXXFLAGS) BTH2_BT04.cpp -o .output/BT04; .output/BT04

5: BTH2_BT05.cpp
	g++ $(CXXFLAGS) BTH2_BT05.cpp -o .output/BT05; .output/BT05

6: BTH2_BT06.cpp
	g++ $(CXXFLAGS) BTH2_BT06.cpp -o .output/BT06; .output/BT06

7: BTH2_BT07.cpp
	g++ $(CXXFLAGS) BTH2_BT07.cpp -o .output/BT07; .output/BT07

8: BTH2_BT08.cpp
	g++ $(CXXFLAGS) BTH2_BT08.cpp -o .output/BT08; .output/BT08

9: BTH2_BT09.cpp
	g++ $(CXXFLAGS) BTH2_BT09.cpp -o .output/BT09; .output/BT09

10: BTH2_BT10.cpp
	g++ $(CXXFLAGS) BTH2_BT10.cpp -o .output/BT10; .output/BT10

11: BTH2_BT11.cpp
	g++ $(CXXFLAGS) BTH2_BT11.cpp -o .output/BT11; .output/BT11

12: BTH2_BT12.cpp
	g++ $(CXXFLAGS) BTH2_BT12.cpp -o .output/BT12; .output/BT12

13: BTH2_BT13.cpp
	g++ $(CXXFLAGS) BTH2_BT13.cpp -o .output/BT13; .output/BT13

clean:
	rm .output/*
