CXXFLAGS = -Wall --std=c++23

1: BTH4_BT01.cpp
	g++ $(CXXFLAGS) BTH4_BT01.cpp -o .output/BT01; .output/BT01

2: BTH4_BT02.cpp
	g++ $(CXXFLAGS) BTH4_BT02.cpp -o .output/BT02; .output/BT02

3: BTH4_BT03.cpp
	g++ $(CXXFLAGS) BTH4_BT03.cpp -o .output/BT03; .output/BT03

4: BTH4_BT04.cpp
	g++ $(CXXFLAGS) BTH4_BT04.cpp -o .output/BT04; .output/BT04

5: BTH4_BT05.cpp
	g++ $(CXXFLAGS) BTH4_BT05.cpp -o .output/BT05; .output/BT05

6: BTH4_BT06.cpp
	g++ $(CXXFLAGS) BTH4_BT06.cpp -o .output/BT06; .output/BT06

7: BTH4_BT07.cpp
	g++ $(CXXFLAGS) BTH4_BT07.cpp -o .output/BT07; .output/BT07

8: BTH4_BT08.cpp
	g++ $(CXXFLAGS) BTH4_BT08.cpp -o .output/BT08; .output/BT08

9: BTH4_BT09.cpp
	g++ $(CXXFLAGS) BTH4_BT09.cpp -o .output/BT09; .output/BT09

10: BTH4_BT10.cpp
	g++ $(CXXFLAGS) BTH4_BT10.cpp -o .output/BT10; .output/BT10

clean:
	rm .output/*
